version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - network1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - network1
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  golang-project-api:
    build:
      context: .
      dockerfile: dev/app/Dockerfile
    ports:
      - 9090:9090
    networks:
      - network1

networks:
  network1:
